/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodRouteImport } from './routes/method'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedNewProjectRouteImport } from './routes/_authenticated/new-project'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAcademyRouteImport } from './routes/_authenticated/academy'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedAcademyModulesIdRouteImport } from './routes/_authenticated/academy.modules.$id'
import { Route as AuthenticatedAcademyLessonsIdRouteImport } from './routes/_authenticated/academy.lessons.$id'

const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewProjectRoute = AuthenticatedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademyRoute = AuthenticatedAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademyModulesIdRoute =
  AuthenticatedAcademyModulesIdRouteImport.update({
    id: '/modules/$id',
    path: '/modules/$id',
    getParentRoute: () => AuthenticatedAcademyRoute,
  } as any)
const AuthenticatedAcademyLessonsIdRoute =
  AuthenticatedAcademyLessonsIdRouteImport.update({
    id: '/lessons/$id',
    path: '/lessons/$id',
    getParentRoute: () => AuthenticatedAcademyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/academy': typeof AuthenticatedAcademyRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/academy': typeof AuthenticatedAcademyRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/_authenticated/academy': typeof AuthenticatedAcademyRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/new-project': typeof AuthenticatedNewProjectRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/_authenticated/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/method'
    | '/academy'
    | '/agents'
    | '/dashboard'
    | '/library'
    | '/new-project'
    | '/tools'
    | '/projects/$id'
    | '/academy/lessons/$id'
    | '/academy/modules/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/method'
    | '/academy'
    | '/agents'
    | '/dashboard'
    | '/library'
    | '/new-project'
    | '/tools'
    | '/projects/$id'
    | '/academy/lessons/$id'
    | '/academy/modules/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/method'
    | '/_authenticated/academy'
    | '/_authenticated/agents'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/new-project'
    | '/_authenticated/tools'
    | '/_authenticated/projects/$id'
    | '/_authenticated/academy/lessons/$id'
    | '/_authenticated/academy/modules/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MethodRoute: typeof MethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-project': {
      id: '/_authenticated/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthenticatedNewProjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy': {
      id: '/_authenticated/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AuthenticatedAcademyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy/modules/$id': {
      id: '/_authenticated/academy/modules/$id'
      path: '/modules/$id'
      fullPath: '/academy/modules/$id'
      preLoaderRoute: typeof AuthenticatedAcademyModulesIdRouteImport
      parentRoute: typeof AuthenticatedAcademyRoute
    }
    '/_authenticated/academy/lessons/$id': {
      id: '/_authenticated/academy/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/academy/lessons/$id'
      preLoaderRoute: typeof AuthenticatedAcademyLessonsIdRouteImport
      parentRoute: typeof AuthenticatedAcademyRoute
    }
  }
}

interface AuthenticatedAcademyRouteChildren {
  AuthenticatedAcademyLessonsIdRoute: typeof AuthenticatedAcademyLessonsIdRoute
  AuthenticatedAcademyModulesIdRoute: typeof AuthenticatedAcademyModulesIdRoute
}

const AuthenticatedAcademyRouteChildren: AuthenticatedAcademyRouteChildren = {
  AuthenticatedAcademyLessonsIdRoute: AuthenticatedAcademyLessonsIdRoute,
  AuthenticatedAcademyModulesIdRoute: AuthenticatedAcademyModulesIdRoute,
}

const AuthenticatedAcademyRouteWithChildren =
  AuthenticatedAcademyRoute._addFileChildren(AuthenticatedAcademyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademyRoute: typeof AuthenticatedAcademyRouteWithChildren
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNewProjectRoute: typeof AuthenticatedNewProjectRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademyRoute: AuthenticatedAcademyRouteWithChildren,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNewProjectRoute: AuthenticatedNewProjectRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MethodRoute: MethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
