/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RiepilogoIdeaRouteImport } from './routes/riepilogo-idea'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as PagamentoSuccessoRouteImport } from './routes/pagamento-successo'
import { Route as MethodRouteImport } from './routes/method'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalizzaIdeaRouteImport } from './routes/analizza-idea'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoadmapSuccessRouteImport } from './routes/_authenticated/roadmap-success'
import { Route as AuthenticatedNewProjectRouteImport } from './routes/_authenticated/new-project'
import { Route as AuthenticatedMyPathRouteImport } from './routes/_authenticated/my-path'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutAgenteRouteImport } from './routes/_authenticated/checkout-agente'
import { Route as AuthenticatedWorkbookProjectIdRouteImport } from './routes/_authenticated/workbook.$projectId'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAcademyModulesIdRouteImport } from './routes/_authenticated/academy.modules.$id'
import { Route as AuthenticatedAcademyLessonsIdRouteImport } from './routes/_authenticated/academy.lessons.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RiepilogoIdeaRoute = RiepilogoIdeaRouteImport.update({
  id: '/riepilogo-idea',
  path: '/riepilogo-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSuccessoRoute = PagamentoSuccessoRouteImport.update({
  id: '/pagamento-successo',
  path: '/pagamento-successo',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizzaIdeaRoute = AnalizzaIdeaRouteImport.update({
  id: '/analizza-idea',
  path: '/analizza-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoadmapSuccessRoute =
  AuthenticatedRoadmapSuccessRouteImport.update({
    id: '/roadmap-success',
    path: '/roadmap-success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewProjectRoute = AuthenticatedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPathRoute = AuthenticatedMyPathRouteImport.update({
  id: '/my-path',
  path: '/my-path',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutAgenteRoute =
  AuthenticatedCheckoutAgenteRouteImport.update({
    id: '/checkout-agente',
    path: '/checkout-agente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbookProjectIdRoute =
  AuthenticatedWorkbookProjectIdRouteImport.update({
    id: '/workbook/$projectId',
    path: '/workbook/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAcademyModulesIdRoute =
  AuthenticatedAcademyModulesIdRouteImport.update({
    id: '/academy/modules/$id',
    path: '/academy/modules/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademyLessonsIdRoute =
  AuthenticatedAcademyLessonsIdRouteImport.update({
    id: '/academy/lessons/$id',
    path: '/academy/lessons/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/agents': typeof AgentsRoute
  '/analizza-idea': typeof AnalizzaIdeaRoute
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/pagamento-successo': typeof PagamentoSuccessoRoute
  '/prezzi': typeof PrezziRoute
  '/pricing': typeof PricingRoute
  '/riepilogo-idea': typeof RiepilogoIdeaRoute
  '/tools': typeof ToolsRoute
  '/checkout-agente': typeof AuthenticatedCheckoutAgenteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-path': typeof AuthenticatedMyPathRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/roadmap-success': typeof AuthenticatedRoadmapSuccessRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/workbook/$projectId': typeof AuthenticatedWorkbookProjectIdRoute
  '/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/agents': typeof AgentsRoute
  '/analizza-idea': typeof AnalizzaIdeaRoute
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/pagamento-successo': typeof PagamentoSuccessoRoute
  '/prezzi': typeof PrezziRoute
  '/pricing': typeof PricingRoute
  '/riepilogo-idea': typeof RiepilogoIdeaRoute
  '/tools': typeof ToolsRoute
  '/checkout-agente': typeof AuthenticatedCheckoutAgenteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-path': typeof AuthenticatedMyPathRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/roadmap-success': typeof AuthenticatedRoadmapSuccessRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/workbook/$projectId': typeof AuthenticatedWorkbookProjectIdRoute
  '/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy': typeof AcademyRoute
  '/agents': typeof AgentsRoute
  '/analizza-idea': typeof AnalizzaIdeaRoute
  '/auth': typeof AuthRoute
  '/method': typeof MethodRoute
  '/pagamento-successo': typeof PagamentoSuccessoRoute
  '/prezzi': typeof PrezziRoute
  '/pricing': typeof PricingRoute
  '/riepilogo-idea': typeof RiepilogoIdeaRoute
  '/tools': typeof ToolsRoute
  '/_authenticated/checkout-agente': typeof AuthenticatedCheckoutAgenteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/my-path': typeof AuthenticatedMyPathRoute
  '/_authenticated/new-project': typeof AuthenticatedNewProjectRoute
  '/_authenticated/roadmap-success': typeof AuthenticatedRoadmapSuccessRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/workbook/$projectId': typeof AuthenticatedWorkbookProjectIdRoute
  '/_authenticated/academy/lessons/$id': typeof AuthenticatedAcademyLessonsIdRoute
  '/_authenticated/academy/modules/$id': typeof AuthenticatedAcademyModulesIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/agents'
    | '/analizza-idea'
    | '/auth'
    | '/method'
    | '/pagamento-successo'
    | '/prezzi'
    | '/pricing'
    | '/riepilogo-idea'
    | '/tools'
    | '/checkout-agente'
    | '/dashboard'
    | '/library'
    | '/my-path'
    | '/new-project'
    | '/roadmap-success'
    | '/projects/$id'
    | '/workbook/$projectId'
    | '/academy/lessons/$id'
    | '/academy/modules/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/agents'
    | '/analizza-idea'
    | '/auth'
    | '/method'
    | '/pagamento-successo'
    | '/prezzi'
    | '/pricing'
    | '/riepilogo-idea'
    | '/tools'
    | '/checkout-agente'
    | '/dashboard'
    | '/library'
    | '/my-path'
    | '/new-project'
    | '/roadmap-success'
    | '/projects/$id'
    | '/workbook/$projectId'
    | '/academy/lessons/$id'
    | '/academy/modules/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy'
    | '/agents'
    | '/analizza-idea'
    | '/auth'
    | '/method'
    | '/pagamento-successo'
    | '/prezzi'
    | '/pricing'
    | '/riepilogo-idea'
    | '/tools'
    | '/_authenticated/checkout-agente'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/my-path'
    | '/_authenticated/new-project'
    | '/_authenticated/roadmap-success'
    | '/_authenticated/projects/$id'
    | '/_authenticated/workbook/$projectId'
    | '/_authenticated/academy/lessons/$id'
    | '/_authenticated/academy/modules/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademyRoute: typeof AcademyRoute
  AgentsRoute: typeof AgentsRoute
  AnalizzaIdeaRoute: typeof AnalizzaIdeaRoute
  AuthRoute: typeof AuthRoute
  MethodRoute: typeof MethodRoute
  PagamentoSuccessoRoute: typeof PagamentoSuccessoRoute
  PrezziRoute: typeof PrezziRoute
  PricingRoute: typeof PricingRoute
  RiepilogoIdeaRoute: typeof RiepilogoIdeaRoute
  ToolsRoute: typeof ToolsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riepilogo-idea': {
      id: '/riepilogo-idea'
      path: '/riepilogo-idea'
      fullPath: '/riepilogo-idea'
      preLoaderRoute: typeof RiepilogoIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-successo': {
      id: '/pagamento-successo'
      path: '/pagamento-successo'
      fullPath: '/pagamento-successo'
      preLoaderRoute: typeof PagamentoSuccessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analizza-idea': {
      id: '/analizza-idea'
      path: '/analizza-idea'
      fullPath: '/analizza-idea'
      preLoaderRoute: typeof AnalizzaIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roadmap-success': {
      id: '/_authenticated/roadmap-success'
      path: '/roadmap-success'
      fullPath: '/roadmap-success'
      preLoaderRoute: typeof AuthenticatedRoadmapSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-project': {
      id: '/_authenticated/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthenticatedNewProjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-path': {
      id: '/_authenticated/my-path'
      path: '/my-path'
      fullPath: '/my-path'
      preLoaderRoute: typeof AuthenticatedMyPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout-agente': {
      id: '/_authenticated/checkout-agente'
      path: '/checkout-agente'
      fullPath: '/checkout-agente'
      preLoaderRoute: typeof AuthenticatedCheckoutAgenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbook/$projectId': {
      id: '/_authenticated/workbook/$projectId'
      path: '/workbook/$projectId'
      fullPath: '/workbook/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkbookProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academy/modules/$id': {
      id: '/_authenticated/academy/modules/$id'
      path: '/academy/modules/$id'
      fullPath: '/academy/modules/$id'
      preLoaderRoute: typeof AuthenticatedAcademyModulesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy/lessons/$id': {
      id: '/_authenticated/academy/lessons/$id'
      path: '/academy/lessons/$id'
      fullPath: '/academy/lessons/$id'
      preLoaderRoute: typeof AuthenticatedAcademyLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutAgenteRoute: typeof AuthenticatedCheckoutAgenteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMyPathRoute: typeof AuthenticatedMyPathRoute
  AuthenticatedNewProjectRoute: typeof AuthenticatedNewProjectRoute
  AuthenticatedRoadmapSuccessRoute: typeof AuthenticatedRoadmapSuccessRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedWorkbookProjectIdRoute: typeof AuthenticatedWorkbookProjectIdRoute
  AuthenticatedAcademyLessonsIdRoute: typeof AuthenticatedAcademyLessonsIdRoute
  AuthenticatedAcademyModulesIdRoute: typeof AuthenticatedAcademyModulesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutAgenteRoute: AuthenticatedCheckoutAgenteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMyPathRoute: AuthenticatedMyPathRoute,
  AuthenticatedNewProjectRoute: AuthenticatedNewProjectRoute,
  AuthenticatedRoadmapSuccessRoute: AuthenticatedRoadmapSuccessRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedWorkbookProjectIdRoute: AuthenticatedWorkbookProjectIdRoute,
  AuthenticatedAcademyLessonsIdRoute: AuthenticatedAcademyLessonsIdRoute,
  AuthenticatedAcademyModulesIdRoute: AuthenticatedAcademyModulesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademyRoute: AcademyRoute,
  AgentsRoute: AgentsRoute,
  AnalizzaIdeaRoute: AnalizzaIdeaRoute,
  AuthRoute: AuthRoute,
  MethodRoute: MethodRoute,
  PagamentoSuccessoRoute: PagamentoSuccessoRoute,
  PrezziRoute: PrezziRoute,
  PricingRoute: PricingRoute,
  RiepilogoIdeaRoute: RiepilogoIdeaRoute,
  ToolsRoute: ToolsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
